-- Harvex database schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run
-- Tables use UUID primary keys generated by Postgres.

-- 1. Farmer inputs ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS farmer_inputs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    crop            TEXT    NOT NULL,
    quantity_kg     NUMERIC NOT NULL,
    quality         TEXT    NOT NULL,   -- 'Premium' | 'Standard' | 'Low'
    farmer_location TEXT    NOT NULL,
    harvest_date    TEXT    NOT NULL,
    shelf_life_days INTEGER NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- 2. Decision results ──────────────────────────────────────────────────────────
-- One row per plan per submission.
-- plan_name values: 'optimize_recommended', 'plan_a', 'plan_b', 'plan_c'
CREATE TABLE IF NOT EXISTS decision_results (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_input_id     UUID    NOT NULL REFERENCES farmer_inputs(id) ON DELETE CASCADE,
    plan_name           TEXT    NOT NULL,
    total_allocated_kg  NUMERIC NOT NULL,
    gross_revenue       NUMERIC NOT NULL,
    transport_cost      NUMERIC NOT NULL,
    spoilage_loss       NUMERIC NOT NULL,
    expected_net_value  NUMERIC NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_decision_results_input
    ON decision_results(farmer_input_id);

-- 3. Allocations ───────────────────────────────────────────────────────────────
-- One row per buyer/market per plan.
CREATE TABLE IF NOT EXISTS allocations (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    decision_result_id      UUID    NOT NULL REFERENCES decision_results(id) ON DELETE CASCADE,
    buyer_name              TEXT    NOT NULL,
    allocated_quantity_kg   NUMERIC NOT NULL,
    selling_price_per_kg    NUMERIC NOT NULL,
    gross_revenue           NUMERIC NOT NULL,
    transport_cost          NUMERIC NOT NULL,
    spoilage_loss           NUMERIC NOT NULL,
    expected_net_value      NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_allocations_result
    ON allocations(decision_result_id);
