-- Harvex database schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run
-- Tables use UUID primary keys generated by Postgres.
-- Steps 21 & 22 additions are marked with [Step 21] / [Step 22].

-- ── [Step 21] Profiles ───────────────────────────────────────────────────────
-- One row per auth.users entry. Created by the backend on first login.
-- role is set once by the user and cannot be changed via the API.
CREATE TABLE IF NOT EXISTS profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role        TEXT    NOT NULL CHECK (role IN ('farmer', 'buyer')),
    full_name   TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- 1. Farmer inputs ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS farmer_inputs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- [Step 21] link each submission to the authenticated farmer
    user_id         UUID    REFERENCES auth.users(id) ON DELETE SET NULL,
    crop            TEXT    NOT NULL,
    quantity_kg     NUMERIC NOT NULL,
    quality         TEXT    NOT NULL,   -- 'Premium' | 'Standard' | 'Low'
    farmer_location TEXT    NOT NULL,
    harvest_date    TEXT    NOT NULL,
    shelf_life_days INTEGER NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- 2. Decision results ──────────────────────────────────────────────────────────
-- One row per plan per submission.
-- plan_name values: 'optimize_recommended', 'plan_a', 'plan_b', 'plan_c'
CREATE TABLE IF NOT EXISTS decision_results (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farmer_input_id     UUID    NOT NULL REFERENCES farmer_inputs(id) ON DELETE CASCADE,
    plan_name           TEXT    NOT NULL,
    total_allocated_kg  NUMERIC NOT NULL,
    gross_revenue       NUMERIC NOT NULL,
    transport_cost      NUMERIC NOT NULL,
    spoilage_loss       NUMERIC NOT NULL,
    expected_net_value  NUMERIC NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_decision_results_input
    ON decision_results(farmer_input_id);

-- 3. Allocations ───────────────────────────────────────────────────────────────
-- One row per buyer/market per plan.
CREATE TABLE IF NOT EXISTS allocations (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    decision_result_id      UUID    NOT NULL REFERENCES decision_results(id) ON DELETE CASCADE,
    buyer_name              TEXT    NOT NULL,
    allocated_quantity_kg   NUMERIC NOT NULL,
    selling_price_per_kg    NUMERIC NOT NULL,
    gross_revenue           NUMERIC NOT NULL,
    transport_cost          NUMERIC NOT NULL,
    spoilage_loss           NUMERIC NOT NULL,
    expected_net_value      NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_allocations_result
    ON allocations(decision_result_id);

-- ── [Step 22] Row Level Security ─────────────────────────────────────────────

-- Enable RLS on all four tables
ALTER TABLE profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE farmer_inputs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE decision_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE allocations      ENABLE ROW LEVEL SECURITY;

-- ── profiles policies ─────────────────────────────────────────────────────────

-- Users can read only their own profile
DROP POLICY IF EXISTS "profiles: owner select" ON profiles;
CREATE POLICY "profiles: owner select"
    ON profiles FOR SELECT
    USING (auth.uid() = id);

-- Users can insert their own profile (role is set on creation, not changed)
DROP POLICY IF EXISTS "profiles: owner insert" ON profiles;
CREATE POLICY "profiles: owner insert"
    ON profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

-- Users cannot update their own role (no UPDATE policy → updates blocked)
-- Backend service-role key bypasses RLS for administrative operations.

-- ── farmer_inputs policies ────────────────────────────────────────────────────

-- A farmer can read their own submissions
DROP POLICY IF EXISTS "farmer_inputs: farmer select" ON farmer_inputs;
CREATE POLICY "farmer_inputs: farmer select"
    ON farmer_inputs FOR SELECT
    USING (
        auth.uid() = user_id
        AND EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'farmer'
        )
    );

-- A farmer can insert only their own submissions
DROP POLICY IF EXISTS "farmer_inputs: farmer insert" ON farmer_inputs;
CREATE POLICY "farmer_inputs: farmer insert"
    ON farmer_inputs FOR INSERT
    WITH CHECK (
        auth.uid() = user_id
        AND EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'farmer'
        )
    );

-- ── decision_results policies ─────────────────────────────────────────────────

-- A farmer can read results for their own farmer_inputs
DROP POLICY IF EXISTS "decision_results: farmer select" ON decision_results;
CREATE POLICY "decision_results: farmer select"
    ON decision_results FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM farmer_inputs fi
            WHERE fi.id = decision_results.farmer_input_id
              AND fi.user_id = auth.uid()
        )
        AND EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'farmer'
        )
    );

-- ── allocations policies ──────────────────────────────────────────────────────

-- A farmer can read allocations for their own decision results
DROP POLICY IF EXISTS "allocations: farmer select" ON allocations;
CREATE POLICY "allocations: farmer select"
    ON allocations FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM decision_results dr
            JOIN farmer_inputs fi ON fi.id = dr.farmer_input_id
            WHERE dr.id = allocations.decision_result_id
              AND fi.user_id = auth.uid()
        )
        AND EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'farmer'
        )
    );

-- ── Anonymous access is blocked by default ────────────────────────────────────
-- No policies grant access to anon role, so anonymous requests are denied
-- on all four tables once RLS is enabled.

-- Note: the backend uses the service_role key which bypasses RLS, so
-- server-side inserts (via /api/submission) continue to work without
-- needing the authenticated user's JWT on the backend.
