import { useEffect, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import type { UserRole } from './lib/roleService';
import { createListing, getListings, getOrders, photoUrl, placeOrder, rateOrderItem, removeProductPhoto, updateOrderItem, uploadProductPhoto, type CropListing } from './lib/marketplaceService';

export default function MarketplacePage({ user, role }: { user: User; role: UserRole }) {
  const [listings,setListings]=useState<CropListing[]>([]); const [search,setSearch]=useState('');
  const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false);
  const [urls,setUrls]=useState<Record<string,string>>({}); const [showAdd,setShowAdd]=useState(false);
  const [form,setForm]=useState({crop_name:'',available_quantity_kg:'',price_per_kg:'',quality:'Standard',harvest_date:'',location:''});
  const [photos,setPhotos]=useState<{file:File;url:string;path?:string}[]>([]);
  const [orders,setOrders]=useState<any[]>([]); const [showOrders,setShowOrders]=useState(false);

  async function load() { setLoading(true); setError(''); try { const rows=await getListings(search); setListings(rows); const pairs=await Promise.all(rows.flatMap(r=>r.photo_paths.slice(0,1).map(async p=>[p,await photoUrl(p)] as const))); setUrls(Object.fromEntries(pairs)); } catch(e){setError(e instanceof Error?e.message:'Could not load listings.');} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);

  async function addPhotos(files: FileList|null){ if(!files)return; setError(''); const chosen=Array.from(files).slice(0,5-photos.length); try { const next:{file:File;url:string;path:string}[]=[]; for(const file of chosen){const path=await uploadProductPhoto(user.id,file);next.push({file,url:URL.createObjectURL(file),path});} setPhotos(p=>[...p,...next]); }catch(e){setError(e instanceof Error?e.message:'Photo upload failed.');}}
  async function removePhoto(index:number){const item=photos[index];if(item.path)await removeProductPhoto(item.path);URL.revokeObjectURL(item.url);setPhotos(p=>p.filter((_,i)=>i!==index));}
  async function submit(e:React.FormEvent){e.preventDefault();setError('');try{await createListing({...form,available_quantity_kg:Number(form.available_quantity_kg),price_per_kg:Number(form.price_per_kg),quality:form.quality as CropListing['quality'],status:'available',photo_paths:photos.flatMap(p=>p.path?[p.path]:[])});setNotice('Listing published.');setShowAdd(false);setPhotos([]);await load();}catch(e){setError(e instanceof Error?e.message:'Could not publish listing.');}}
  async function order(row:CropListing){const raw=window.prompt(`Quantity in kg (available: ${row.available_quantity_kg})`);if(!raw)return;setError('');try{const result=await placeOrder(row.crop_name,Number(raw),row.quality);setNotice(`Order ${result.order_id} placed and fairly allocated.`);await load();}catch(e){setError(e instanceof Error?e.message:'Order failed.');}}
  async function loadOrders(){try{setOrders(await getOrders());setShowOrders(true);}catch(e){setError(e instanceof Error?e.message:'Could not load orders.');}}
  async function changeStatus(id:string,status:string){try{await updateOrderItem(id,status);setNotice(`Order marked ${status}.`);await loadOrders();}catch(e){setError(e instanceof Error?e.message:'Status update failed.');}}
  async function rate(id:string){const value=Number(window.prompt('Rating from 1 to 5'));if(!value)return;const review=window.prompt('Optional review')??'';try{await rateOrderItem(id,value,review);setNotice('Thank you. Your rating was saved.');await loadOrders();}catch(e){setError(e instanceof Error?e.message:'Rating failed.');}}

  return <div className="w-full max-w-5xl space-y-5">
    <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Crop Marketplace</h1><p className="text-sm text-gray-500">Actual farmer produce, protected photos, transparent stock and prices.</p></div><div className="flex gap-2"><button onClick={()=>void loadOrders()} className="px-5 py-3 border rounded-xl font-semibold">Orders</button>{role==='farmer'&&<button onClick={()=>setShowAdd(v=>!v)} className="px-5 py-3 bg-green-600 text-white rounded-xl font-semibold">{showAdd?'Close':'＋ Add Crop'}</button>}</div></div>
    {error&&<div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-xl">{error}</div>}{notice&&<div className="p-3 bg-green-50 border border-green-200 text-green-700 rounded-xl">{notice}</div>}
    {showAdd&&<form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4"><h2 className="font-bold">New crop listing</h2><div className="grid sm:grid-cols-2 gap-3">{[['crop_name','Crop name'],['available_quantity_kg','Quantity (kg)'],['price_per_kg','Price per kg'],['location','Location'],['harvest_date','Harvest date']].map(([k,l])=><label className="text-sm" key={k}>{l}<input required type={k==='harvest_date'?'date':k.includes('quantity')||k.includes('price')?'number':'text'} min="0" step="0.01" value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full border rounded-xl px-3 py-2"/></label>)}<label className="text-sm">Quality<select value={form.quality} onChange={e=>setForm({...form,quality:e.target.value})} className="mt-1 w-full border rounded-xl px-3 py-2"><option>Premium</option><option>Standard</option><option>Low</option></select></label></div>
      <label className="block border-2 border-dashed rounded-xl p-4 text-center cursor-pointer">📷 Take or upload actual product photos<input className="hidden" type="file" accept="image/*" capture="environment" multiple onChange={e=>void addPhotos(e.target.files)}/></label><div className="flex gap-3 flex-wrap">{photos.map((p,i)=><div key={p.url} className="relative"><img src={p.url} className="w-24 h-24 object-cover rounded-xl"/><button type="button" onClick={()=>void removePhoto(i)} className="absolute -top-2 -right-2 bg-red-600 text-white rounded-full w-6">×</button></div>)}</div><button className="w-full bg-green-600 text-white py-3 rounded-xl font-semibold">Publish listing</button></form>}
    {showOrders&&<section className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><h2 className="font-bold">Order history</h2><button onClick={()=>setShowOrders(false)}>×</button></div><div className="mt-3 space-y-3">{orders.length===0?<p className="text-sm text-gray-400">No orders yet.</p>:orders.map((o:any)=><div key={o.id} className="border rounded-xl p-3 text-sm"><div className="flex justify-between"><b>{o.crop_name??o.crop_listings?.crop_name??'Crop order'}</b><span>{o.status}</span></div><p>{o.quantity_kg??o.requested_quantity_kg} kg {o.total_price!=null&&`· ₹${o.total_price}`}</p>{role==='farmer'&&['Pending','Accepted','Processing','Ready'].includes(o.status)&&<div className="flex flex-wrap gap-1 mt-2">{['Accepted','Rejected','Processing','Ready','Completed'].map(s=><button key={s} onClick={()=>void changeStatus(o.id,s)} className="border px-2 py-1 rounded-lg">{s}</button>)}</div>}{role!=='farmer'&&o.order_items?.map((item:any)=>item.status==='Completed'&&!item.farmer_ratings?.length?<button key={item.id} onClick={()=>void rate(item.id)} className="mt-2 px-3 py-1 bg-amber-500 text-white rounded-lg">Rate Farmer</button>:null)}</div>)}</div></section>}
    <div className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search crops" className="flex-1 border rounded-xl px-4 py-3"/><button onClick={()=>void load()} className="px-5 rounded-xl bg-gray-900 text-white">Search</button></div>
    {loading?<p className="text-center text-gray-400">Loading…</p>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{listings.map(row=><article key={row.id} className="bg-white border rounded-2xl overflow-hidden shadow-sm">{row.photo_paths[0]&&<button className="w-full" onClick={()=>window.open(urls[row.photo_paths[0]],'_blank')}><img src={urls[row.photo_paths[0]]} className="w-full h-44 object-cover"/></button>}<div className="p-4 space-y-2"><div className="flex justify-between"><h2 className="font-bold text-lg">{row.crop_name}</h2><span className="font-bold text-green-700">₹{row.price_per_kg}/kg</span></div><p className="text-sm">{row.quality} · {row.available_quantity_kg} kg available</p><p className="text-xs text-gray-500">Harvested {row.harvest_date} · 📍 {row.location}</p><p className="text-xs">Farmer {row.profiles?.public_id??'—'} · ⭐ {Number(row.profiles?.average_rating??0).toFixed(2)} ({row.profiles?.total_ratings??0})</p>{role!=='farmer'&&<button onClick={()=>void order(row)} className="w-full mt-2 py-2 bg-blue-600 text-white rounded-xl font-semibold">Place order</button>}</div></article>)}</div>}
  </div>;
}
